//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCanteenWebshop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AGCanteenWebShopEntities : DbContext
    {
        public AGCanteenWebShopEntities()
            : base("name=AGCanteenWebShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Customer> Tbl_Customer { get; set; }
        public virtual DbSet<Tbl_CustomerRole> Tbl_CustomerRole { get; set; }
        public virtual DbSet<Tbl_Lunch> Tbl_Lunch { get; set; }
        public virtual DbSet<Tbl_LunchOrderDetail> Tbl_LunchOrderDetail { get; set; }
        public virtual DbSet<Tbl_Order> Tbl_Order { get; set; }
        public virtual DbSet<Tbl_OrderDetail> Tbl_OrderDetail { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<Tbl_ProductCategory> Tbl_ProductCategory { get; set; }
    }
}
